language: generic

dist: focal

## Uncomment the following lines if you require extra dependencies
before_install:
# - sudo apt-get install ghostscript # If you use latex > dvips > ps2pdf
# - sudo apt-get install python-pygments # If you use the minted package
  # If you use custom fonts:
# - mkdir $HOME/.fonts
# - cp -a $TRAVIS_BUILD_DIR/src/fonts/. $HOME/.fonts/
# - fc-cache -f -v
  - sudo apt-get install biber -y
  - echo 'Check biber version...' && biber --version
  - tlmgr install hyphen-german
     
install:
  - cd $TRAVIS_BUILD_DIR/
  - source ./texlive/texlive_install.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

# Change working directory so including files will work
before_script:
  - cd $TRAVIS_BUILD_DIR/src/
script:
  - texliveonfly script.tex || true # Texliveonfly will download packages automatically #ignore errors here because tex will be recompiled
  # You can use latexmk to automatically handle bibtex and references (recommended)
  #- latexmk -pdf script.tex
  - pdflatex -synctex=1 -interaction=nonstopmode script.tex -shell-escape || true # as preparation in order to run biber.
  - biber script
  - pdflatex -synctex=1 -interaction=nonstopmode script.tex -shell-escape > custom_log.log
  - cat custom_log.log
  - cat custom_log.log | grep -E 'at\s*line(s|)\s*[0-9]+' > custom_errors.log || true
  - $TRAVIS_BUILD_DIR/script/check_empty.sh
  - cat custom_errors.log
  - mv script.pdf $TRAVIS_BUILD_DIR/build/


  # But you could use any other compiler as well instead of latexmk. Example:
#  - pdflatex main.tex
#  - bibtex main
#  - pdflatex main.tex
#  - pdflatex main.tex # Compile twice to fix references

  # You can also pass arguments to texliveonfly:
#  - texliveonfly --arguments='-shell-escape' main.tex

## Uncomment the following lines to see the packages installed in travis
#after_script:
#  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
#  - tlmgr list --only-installed | grep -oP 'i \K.+?(?=:)'

deploy:
    provider: pages
    skip_cleanup: true
    token: $GH_REPO_TOKEN
    keep_history: true
    local_dir: build
    target_branch: gh-pages
    on :
        branch: master
